"""Execute the production IRBuilder expressions for the ARM64 SPU batch.

Both architecture branches are read from production. Unsupported statements or
operations fail explicitly. The byte-insert baseline is LLVM insertelement,
the operation generated by the pre-existing SHUFB peephole.
"""
from pathlib import Path
import re
import sys

SOURCE = Path(__file__).resolve().parents[3] / 'rpcs3/Emu/Cell/SPULLVMRecompiler.cpp'


def args(text):
    result, depth, start = [], 0, 0
    for i, c in enumerate(text):
        if c in '({': depth += 1
        if c in ')}': depth -= 1
        if c == ',' and not depth:
            result.append(text[start:i].strip()); start = i + 1
    return result + [text[start:].strip()]


def typ(cpp):
    m = re.fullmatch(r'([usf])(\d+)(?:\[(\d+)\])?', cpp)
    assert m, cpp
    base = ('double' if m[2] == '64' else 'float') if m[1] == 'f' else 'i' + m[2]
    return f'<{m[3]} x {base}>' if m[3] else base


def vector_info(t):
    m = re.fullmatch(r'<(\d+) x (\w+)>', t)
    return int(m[1]), m[2]


class IR:
    helpers = {}
    def __init__(self, values): self.values, self.lines = values, []

    def emit(self, t, instruction):
        name = '%v' + str(len(self.lines))
        self.lines.append(f'  {name} = {instruction}')
        return t, name

    def expr(self, text):
        text = text.strip()
        if text in self.values: return self.values[text]
        if m := re.fullmatch(r'(\w+)\((.*)\)', text):
            if m[1] in self.helpers:
                expressions = [self.expr(a) for a in args(m[2])]
                params, source = self.helpers[m[1]]
                saved = self.values
                self.values = dict(zip(params, expressions))
                result = self.body(source)
                self.values = saved
                return result
            if m[1] == 'abs_double':
                t, value = self.expr(m[2])
                return self.emit(t, f'call {t} @llvm.fabs.v4f64({t} {value})')
        if re.fullmatch(r'0x[0-9a-f]+|[0-9]+', text): return 'literal', int(text, 0)
        if m := re.fullmatch(r'(f?splat|build)<([^>]+)>\((.*)\).eval\(m_ir\)', text):
            t = typ(m[2]); count, base = vector_info(t)
            values = args(m[3])
            if m[1] != 'build': values *= count
            assert len(values) == count
            values = [str(float(v)) if base in ('double', 'float') else str(int(v, 0)) for v in values]
            return t, '<' + ', '.join(f'{base} {v}' for v in values) + '>'
        if m := re.fullmatch(r'bitcast<([^>]+)>\((.*)\)', text):
            st, value = self.expr(m[2]); t = typ(m[1])
            return self.emit(t, f'bitcast {st} {value} to {t}')
        if m := re.fullmatch(r'(double_as_uint64|uint64_as_double)\((.*)\)', text):
            st, value = self.expr(m[2]); t = '<4 x i64>' if m[1] == 'double_as_uint64' else '<4 x double>'
            return self.emit(t, f'bitcast {st} {value} to {t}')
        m = re.fullmatch(r'm_ir->Create(\w+)\((.*)\)', text)
        if not m: raise ValueError(f'Unsupported expression: {text}')
        op, a = m[1], args(m[2])
        if op == 'VectorSplat':
            count = int(a[0]); st, value = self.expr(a[1]); t = f'<{count} x {st}>'
            _, v = self.emit(t, f'insertelement {t} poison, {st} {value}, i32 0')
            return self.emit(t, f'shufflevector {t} {v}, {t} poison, <{count} x i32> zeroinitializer')
        lt, left = self.expr(a[0])
        if op in ('ZExt', 'SExt', 'Trunc'):
            mt = re.fullmatch(r'get_type<([^>]+)>\(\)', a[1]); assert mt
            t = typ(mt[1]); return self.emit(t, f'{op.lower()} {lt} {left} to {t}')
        if op == 'IsNotNull':
            count, _ = vector_info(lt)
            return self.emit(f'<{count} x i1>', f'icmp ne {lt} {left}, zeroinitializer')
        if op == 'Select':
            rt, right = self.expr(a[1]); ft, false = self.expr(a[2]); assert rt == ft
            return self.emit(rt, f'select {lt} {left}, {rt} {right}, {ft} {false}')
        rt, right = self.expr(a[1])
        if op == 'ShuffleVector':
            indices = [int(v) for v in a[2].strip('{}').split(',')]
            assert lt == rt
            _, base = vector_info(lt); mask = '<' + ', '.join(f'i32 {v}' for v in indices) + '>'
            return self.emit(f'<{len(indices)} x {base}>', f'shufflevector {lt} {left}, {rt} {right}, <{len(indices)} x i32> {mask}')
        if op == 'InsertElement':
            it, index = self.expr(a[2])
            return self.emit(lt, f'insertelement {lt} {left}, {rt} {right}, {it} {index}')
        count, base = vector_info(lt)
        if rt == 'literal':
            right = '<' + ', '.join([f'{base} {right}'] * count) + '>'; rt = lt
        assert lt == rt
        if op.startswith(('ICmp', 'FCmp')):
            return self.emit(f'<{count} x i1>', f'{op[:4].lower()} {op[4:].lower()} {lt} {left}, {right}')
        operations = {'And': 'and', 'Or': 'or', 'Xor': 'xor', 'Add': 'add', 'Shl': 'shl', 'LShr': 'lshr', 'AShr': 'ashr'}
        return self.emit(lt, f'{operations[op]} {lt} {left}, {right}')

    def body(self, body):
        body = re.sub(r'//[^\n]*', '', body)
        output = None
        for statement in body.split(';'):
            statement = statement.strip()
            if not statement or statement.startswith('ensure('): continue
            if m := re.fullmatch(r'const auto (\w+) = (.*)', statement, re.S): self.values[m[1]] = self.expr(m[2])
            elif statement.startswith('return '): output = self.expr(statement[7:])
            else: raise ValueError(f'Unsupported statement: {statement}')
        assert output
        return output


def body(source, name):
    start = source.index('{', source.index('llvm::Value* ' + name + '('))
    depth = 1; end = start
    while depth:
        end += 1
        if source[end] == '{': depth += 1
        if source[end] == '}': depth -= 1
    return source[start + 1:end]


def pair(source, name):
    text = body(source, name)
    before, rest = text.split('#ifdef ARCH_ARM64', 1)
    new, old = rest.split('#else', 1)
    old = old.rsplit('#endif', 1)[0]
    old = re.sub(r'#ifdef ARCH_X64.*?#endif', '', old, flags=re.S)
    return before + old, before + new


def batch(body, name, input_type, output_type):
    ir = IR({'val': (input_type, '%input')}); rt, result = ir.body(body); assert rt == output_type
    _, ib = vector_info(input_type); _, ob = vector_info(output_type)
    return f'''define void @{name}(ptr %src, ptr %dst, i64 %count) {{
entry:
  br label %loop
loop:
  %i = phi i64 [ 0, %entry ], [ %next, %loop ]
  %sp = getelementptr {ib}, ptr %src, i64 %i
  %dp = getelementptr {ob}, ptr %dst, i64 %i
  %input = load {input_type}, ptr %sp, align 4
{chr(10).join(ir.lines)}
  store {output_type} {result}, ptr %dp, align 4
  %next = add i64 %i, 4
  %again = icmp ult i64 %next, %count
  br i1 %again, label %loop, label %end
end:
  ret void
}}
'''


def insertion(body, name):
    t = '<16 x i8>'
    ir = IR({'vector': (t, '%vector'), 'element': ('i8', '%element'), 'index': ('i32', '%index')})
    rt, result = ir.body(body); assert rt == t
    return f'''define void @{name}(ptr %src, ptr %elements, ptr %indices, ptr %dst, i64 %count) {{
entry:
  %initial = load {t}, ptr %src, align 1
  br label %loop
loop:
  %i = phi i64 [ 0, %entry ], [ %next, %loop ]
  %vector = phi {t} [ %initial, %entry ], [ {result}, %loop ]
  %ep = getelementptr i8, ptr %elements, i64 %i
  %ip = getelementptr i32, ptr %indices, i64 %i
  %element = load i8, ptr %ep, align 1
  %rawindex = load i32, ptr %ip, align 4
  %index = and i32 %rawindex, 15
{chr(10).join(ir.lines)}
  %next = add i64 %i, 1
  %again = icmp ult i64 %next, %count
  br i1 %again, label %loop, label %end
end:
  store {t} {result}, ptr %dst, align 1
  ret void
}}
'''


def comparison(body, name):
    t = '<4 x i32>'
    ir = IR({'a': (t, '%a'), 'b': (t, '%b')}); rt, result = ir.body(body); assert rt == t
    return f'''define void @{name}(ptr %lhs, ptr %rhs, ptr %dst, i64 %count) {{
entry:
  br label %loop
loop:
  %i = phi i64 [ 0, %entry ], [ %next, %loop ]
  %ap = getelementptr i32, ptr %lhs, i64 %i
  %bp = getelementptr i32, ptr %rhs, i64 %i
  %dp = getelementptr i32, ptr %dst, i64 %i
  %a = load {t}, ptr %ap, align 4
  %b = load {t}, ptr %bp, align 4
{chr(10).join(ir.lines)}
  store {t} {result}, ptr %dp, align 4
  %next = add i64 %i, 4
  %again = icmp ult i64 %next, %count
  br i1 %again, label %loop, label %end
end:
  ret void
}}
'''


def main(output):
    source = SOURCE.read_text(); functions = []
    IR.helpers = {name: (['val'], body(source, name)) for name in ('canonical_spu_xfloat', 'spu_xfloat_order_key')}
    IR.helpers['xfloat_to_double'] = (['val'], pair(source, 'xfloat_to_double')[1])
    for name, alias, it, ot in [
        ('double_to_xfloat', 'pack', '<4 x double>', '<4 x i32>'),
        ('conv_xfloat_mask', 'mask', '<4 x i32>', '<4 x i64>'),
    ]:
        old, new = pair(source, name)
        functions += [batch(old, alias + '_baseline', it, ot), batch(new, alias + '_candidate', it, ot)]
    functions += [insertion('return m_ir->CreateInsertElement(vector, element, index);', 'insert_baseline'),
                  insertion(body(source, 'insert_spu_byte'), 'insert_candidate')]
    for op, predicate, magnitude in [('gt', 'OGT', False), ('eq', 'OEQ', False), ('mgt', 'OGT', True), ('meq', 'OEQ', True)]:
        a, b = 'xfloat_to_double(a)', 'xfloat_to_double(b)'
        if magnitude: a, b = f'abs_double({a})', f'abs_double({b})'
        old = f'return m_ir->CreateSExt(m_ir->CreateFCmp{predicate}({a}, {b}), get_type<u32[4]>());'
        functions += [comparison(old, op + '_baseline'), comparison(body(source, 'compare_spu_xfloat_' + op), op + '_candidate')]
    Path(output).write_text('declare <4 x double> @llvm.fabs.v4f64(<4 x double>)\n\n' + '\n'.join(functions))


if __name__ == '__main__': main(sys.argv[1])
