#!/usr/bin/env python3
"""Compare extracted production paths against the immutable pre-batch reference."""
from pathlib import Path
import argparse,subprocess,os,tempfile,json
HERE=Path(__file__).resolve().parent;CORE=HERE.parents[2]
p=argparse.ArgumentParser();p.add_argument('--candidate-root',type=Path,default=CORE);p.add_argument('--sanitize',action='store_true');p.add_argument('--benchmark',action='store_true');args=p.parse_args()
def block(s,marker):
 a=s.index(marker);b=s.index('{',a)+1;depth=1
 while depth:
  depth+=(s[b]=='{')-(s[b]=='}');b+=1
 return s[a:b]
def extract(root):
 spu=(root/'rpcs3/Emu/Cell/SPUThread.cpp').read_text()
 cache=(root/'rpcs3/Emu/RSX/rsx_cache.h').read_text()
 vertex=(root/'rpcs3/Emu/RSX/Core/RSXVertexTypes.h').read_text()
 return {
 'cmp':block(spu,'static FORCE_INLINE int16x8_t cmp16_pair_accum_arm64(')+'\n'+block(spu,'extern bool cmp_rdata('),
 'cache':block(cache,'class weak_vertex_cache')+';',
 'validate':block(vertex,'bool validate() const'),
 'dirty':block((root/'rpcs3/Emu/RSX/VK/VKProgramPipeline.h').read_text(),'inline void notify_descriptor_slot_updated('),
 }
# The baseline files are committed source snapshots, never regenerated by tests.
new=extract(args.candidate_root)
with tempfile.TemporaryDirectory(prefix='minecraft-perf-') as d:
 t=Path(d)
 for name,s in new.items():
  (t/('new-'+name+'.inc')).write_text(s)
  (t/('old-'+name+'.inc')).write_bytes((HERE/'MinecraftReference'/(name+'.inc')).read_bytes())
 header=(args.candidate_root/'rpcs3/Emu/RSX/VK/VKProgramPipeline.h').read_text()
 (t/'dirty-type.inc').write_text('using dirty_type = std::vector<'+('bool' if 'std::vector<bool> m_descriptors_dirty;' in header else 'u8')+'>;')
 cmd=[os.environ.get('CXX','clang++'),'-std=c++20','-O2','-Wall','-Wextra','-Werror','-pthread','-I',str(t),'-I',str(CORE/'rpcs3'),'-I',str(CORE),'-I',str(CORE/'3rdparty/asmjit/asmjit/src'),'-I',str(CORE/'3rdparty/unordered_dense/include'),str(HERE/'MinecraftOptimizationTests.cpp'),'-o',str(t/'test')]
 if args.sanitize:cmd[1:1]=['-fsanitize=address,undefined','-fno-omit-frame-pointer']
 subprocess.run(cmd,check=True)
 subprocess.run([str(t/'test'),*(['benchmark'] if args.benchmark else [])],check=True)
