#include "Emu/CPU/Backends/AArch64/SPUInterpreterGateway.h"

#include <array>
#include <cassert>
#include <cstddef>
#include <cstdio>

using namespace asmjit;
struct alignas(16) Context
{
	// Exercise a context offset too large for a single ADD immediate.
	std::array<std::uint8_t, 0x12340> padding{};
	std::uint64_t pc = 0, sp = 0;
	std::array<std::uint64_t, 19> observed{};
	unsigned calls = 0;
};
using Entry = void (*)(Context*, void*, void*);

// Generated by the runner from the production ARM64 spu_escape emitter.
#include "SPUEscapeUnderTest.h"

struct Errors : ErrorHandler
{
	void handleError(Error error, const char*, BaseEmitter*) override { assert(error == kErrorOk); }
};

template <typename F> Entry build(JitRuntime& runtime, F emit)
{
	CodeHolder code;
	assert(code.init(runtime.environment()) == kErrorOk);
	Errors errors;
	code.setErrorHandler(&errors);
	a64::Assembler c(&code);
	emit(c);
	Entry entry = nullptr;
	assert(runtime.add(&entry, &code) == kErrorOk);
	return entry;
}

void normal(Context* context, void* ls, void* rip)
{
	assert(ls == context->padding.data() && rip == context->observed.data());
	assert(context->pc && context->sp && context->pc != context->sp);
	++context->calls;
}

int main()
{
	JitRuntime runtime;
	const auto escape = build(runtime, [](a64::Assembler& c) { emit_production_escape(c); });
	const auto aborting = build(runtime, [&](a64::Assembler& c)
	{
		// Model an opcode/helper that leaves multiple native frames and dirty
		// callee-saved registers behind when it exits via the real escape code.
		c.sub(a64::sp, a64::sp, Imm(1024));
		for (unsigned i = 19; i <= 29; ++i) c.mov(a64::GpX(i), Imm(0xbad));
		for (unsigned i = 8; i <= 15; ++i) c.fmov(a64::VecD(i), a64::x19);
		c.mov(a64::x16, Imm(reinterpret_cast<std::uint64_t>(escape)));
		c.br(a64::x16);
	});

	for (const auto target : {&normal, aborting})
	{
		const auto gateway = build(runtime, [&](a64::Assembler& c)
		{
			aarch64::emit_spu_interpreter_gateway(c, offsetof(Context, pc), reinterpret_cast<std::uint64_t>(target));
		});
		const auto probe = build(runtime, [&](a64::Assembler& c)
		{
			// Independently preserve the test caller, seed every native callee-save
			// register, and record what survives the gateway. x18 is platform-owned.
			c.sub(a64::sp, a64::sp, Imm(192));
			for (unsigned i = 19; i <= 30; ++i) c.str(a64::GpX(i), arm::Mem(a64::sp, (i - 19) * 8));
			for (unsigned i = 8; i <= 15; ++i) c.str(a64::VecD(i), arm::Mem(a64::sp, 96 + (i - 8) * 8));
			c.str(a64::x0, arm::Mem(a64::sp, 160));
			c.str(a64::x18, arm::Mem(a64::sp, 168));
			for (unsigned i = 19; i <= 29; ++i) c.mov(a64::GpX(i), Imm(0x12340000 + i));
			for (unsigned i = 8; i <= 15; ++i)
			{
				c.mov(a64::x16, Imm(0x56780000 + i));
				c.fmov(a64::VecD(i), a64::x16);
			}
			c.mov(a64::x16, Imm(reinterpret_cast<std::uint64_t>(gateway)));
			c.blr(a64::x16);
			c.ldr(a64::x0, arm::Mem(a64::sp, 160));
			c.mov(a64::x16, Imm(offsetof(Context, observed)));
			c.add(a64::x16, a64::x16, a64::x0);
			for (unsigned i = 19; i <= 29; ++i) c.str(a64::GpX(i), arm::Mem(a64::x16, (i - 19) * 8));
			for (unsigned i = 8; i <= 15; ++i) c.str(a64::VecD(i), arm::Mem(a64::x16, 88 + (i - 8) * 8));
			c.ldr(a64::x16, arm::Mem(a64::sp, 168));
			c.cmp(a64::x18, a64::x16);
			const auto platform_register_ok = c.newLabel();
			c.b_eq(platform_register_ok);
			c.brk(0x42);
			c.bind(platform_register_ok);
			for (unsigned i = 19; i <= 30; ++i) c.ldr(a64::GpX(i), arm::Mem(a64::sp, (i - 19) * 8));
			for (unsigned i = 8; i <= 15; ++i) c.ldr(a64::VecD(i), arm::Mem(a64::sp, 96 + (i - 8) * 8));
			c.add(a64::sp, a64::sp, Imm(192));
			c.ret(a64::x30);
		});
		Context context;
		for (unsigned iteration = 0; iteration < 10000; ++iteration)
		{
			probe(&context, context.padding.data(), context.observed.data());
			for (unsigned i = 19; i <= 29; ++i) assert(context.observed[i - 19] == 0x12340000 + i);
			for (unsigned i = 8; i <= 15; ++i) assert(context.observed[11 + i - 8] == 0x56780000 + i);
		}
		assert(context.calls == (target == &normal ? 10000 : 0));
	}
	std::puts("20,000 ARM64 interpreter gateway returns/escapes passed: arguments, PC/SP, GP/SIMD registers and repeated stack restoration");
}
